"""Tests for the supported package-root API contract."""

from __future__ import annotations

import PermutiveAPI


CANONICAL_EXPORTS = {
    "API_CONTRACT_VERSION",
    "AliasPayload",
    "ArtifactDigest",
    "AsyncPermutiveClient",
    "AsyncResource",
    "AsyncResponse",
    "AsyncResponseLike",
    "AsyncTransport",
    "AsyncTransportLike",
    "AtomicCredentials",
    "AuthenticationError",
    "AuthorizationError",
    "BatchItem",
    "BatchResult",
    "CAPABILITY_CONTRACT_VERSION",
    "CAPABILITY_ERROR_CODES",
    "CapabilityDescriptor",
    "CapabilityNegotiationError",
    "CapabilityRequirement",
    "ConflictError",
    "ContextPayload",
    "CoordinatedAsyncTransport",
    "CoordinatedTransport",
    "CredentialSnapshot",
    "DecodingError",
    "DriftKind",
    "EndpointContract",
    "ErrorGuidance",
    "EventPayload",
    "FIRST_SUCCESS_BUDGET_SECONDS",
    "FIRST_SUCCESS_CONTRACT_VERSION",
    "FIRST_SUCCESS_RECIPE",
    "FirstSuccessMeasurement",
    "IdentityPayload",
    "JSONObject",
    "JSONScalar",
    "JSONSchema",
    "JSONValue",
    "NotFoundError",
    "PERFORMANCE_CONTRACT_VERSION",
    "PERMUTIVE_MCP_DOCUMENTATION_URL",
    "PERMUTIVE_MCP_SERVER_NAME",
    "PERMUTIVE_MCP_TOKEN_ENV",
    "PERMUTIVE_MCP_URL_ENV",
    "Page",
    "PerformanceBudget",
    "PerformanceResult",
    "PermutiveAgentKit",
    "PermutiveClient",
    "PermutiveConfig",
    "PermutiveMCPConfig",
    "QueryExpression",
    "RECORDING_FORMAT_VERSION",
    "RELEASE_EVIDENCE_VERSION",
    "RateLimitCoordinator",
    "RateLimitError",
    "Recipe",
    "RecipeCategory",
    "RecordedInteraction",
    "Recording",
    "RecordingTransport",
    "ReplayMismatchError",
    "ReplayTransport",
    "Resource",
    "ResponseKind",
    "RetryPolicy",
    "SDKError",
    "SchemaDrift",
    "SchemaDriftError",
    "Secret",
    "SegmentationPayload",
    "ServerError",
    "SyncTransport",
    "TOOL_SCHEMA_VERSION",
    "ToolDefinition",
    "ToolHandler",
    "ToolRegistry",
    "TransportError",
    "ValidationError",
    "all_of",
    "any_of",
    "capability_contract_manifest",
    "classify_exception",
    "classify_response_schema",
    "contract_manifest",
    "create_release_manifest",
    "digest_file",
    "endpoint_contract",
    "endpoint_contracts",
    "event",
    "execute_async_batch",
    "execute_batch",
    "find_recipes",
    "first_success_contract",
    "in_segment",
    "load_performance_budgets",
    "measure_first_success",
    "measure_operation",
    "negotiate_capabilities",
    "performance_report",
    "property_condition",
    "recipe_catalog",
    "recipe_manifest",
    "sanitize_json",
    "schema_fingerprint",
    "structural_schema",
    "tool",
    "validate_operation_names",
    "validate_response_schema",
    "verify_release_manifest",
    "write_release_manifest",
}

COMPATIBILITY_EXPORTS = {
    "Alias",
    "Cohort",
    "CohortList",
    "ContextSegment",
    "Event",
    "Identity",
    "Import",
    "ImportList",
    "PermutiveAPIError",
    "PermutiveAuthenticationError",
    "PermutiveBadRequestError",
    "PermutiveRateLimitError",
    "PermutiveResourceNotFoundError",
    "PermutiveServerError",
    "Segment",
    "SegmentList",
    "Segmentation",
    "Source",
    "Workspace",
    "WorkspaceList",
}


def test_public_exports_are_fully_classified() -> None:
    """Require every package-root export to have an explicit support class."""
    classified = CANONICAL_EXPORTS | COMPATIBILITY_EXPORTS

    assert set(PermutiveAPI.__all__) == classified


def test_public_exports_are_available() -> None:
    """Require every declared public export to resolve from the package root."""
    for name in PermutiveAPI.__all__:
        assert getattr(PermutiveAPI, name) is not None


def test_public_export_names_are_unique() -> None:
    """Keep the package-root contract deterministic and unambiguous."""
    assert len(PermutiveAPI.__all__) == len(set(PermutiveAPI.__all__))
