"""Generate or validate API contract and coverage evidence."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Mapping

from PermutiveAPI.contracts import contract_manifest, endpoint_contracts
from PermutiveAPI.sdk import JSONValue

SAMPLES_PATH = Path("contracts/api-samples-v1.json")
MANIFEST_PATH = Path("contracts/api-contract-v1.json")
COVERAGE_PATH = Path("API_COVERAGE.md")


def _samples(path: Path) -> Mapping[str, JSONValue]:
    decoded: object = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(decoded, dict) or decoded.get("version") != 1:
        raise ValueError("API samples must use contract version 1.")
    samples = decoded.get("samples")
    if not isinstance(samples, dict) or not all(
        isinstance(name, str) for name in samples
    ):
        raise TypeError("API samples must be a string-keyed object.")
    return samples  # type: ignore[return-value]


def _markdown(manifest: Mapping[str, object]) -> str:
    lines = [
        "# API Coverage",
        "",
        "Generated from `contracts/api-samples-v1.json` and the canonical endpoint registry.",
        "Do not edit this file manually.",
        "",
        "| Contract | Method | Path | Response | Mutating | Schema fingerprint |",
        "|---|---:|---|---|---:|---|",
    ]
    schemas = manifest["schemas"]
    if not isinstance(schemas, dict):
        raise TypeError("Contract manifest schemas must be an object.")
    for contract in endpoint_contracts():
        schema = schemas[contract.name]
        if not isinstance(schema, dict):
            raise TypeError("Contract schema evidence must be an object.")
        fingerprint = schema["fingerprint"]
        lines.append(
            "| "
            f"`{contract.name}` | `{contract.method}` | `{contract.path_template}` | "
            f"`{contract.response_kind.value}` | "
            f"{'yes' if contract.mutating else 'no'} | `{fingerprint}` |"
        )
    lines.extend(
        [
            "",
            "## Drift policy",
            "",
            "- Unchanged structural fingerprints pass silently.",
            "- Additive fields or response variants are reported as compatible drift.",
            "- Removed fields, removed variants, and type changes are breaking and fail validation.",
            "- Default tests remain network-free; live validation is explicit and credential-gated.",
            "",
        ]
    )
    return "\n".join(lines)


def _write_or_check(path: Path, expected: str, *, check: bool) -> None:
    if check:
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            raise SystemExit(f"Generated evidence is stale: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")


def main() -> int:
    """Generate evidence or fail when committed evidence is stale."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    manifest = contract_manifest(_samples(SAMPLES_PATH))
    manifest_text = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    coverage_text = _markdown(manifest)
    _write_or_check(MANIFEST_PATH, manifest_text, check=args.check)
    _write_or_check(COVERAGE_PATH, coverage_text, check=args.check)
    print(f"API contract validation passed for {len(endpoint_contracts())} operations.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
